import { NgModule } from '@angular/core';
import {
    BlockColorSubmenuUI,
    BlockControlsUI,
    BlockMenuUI,
    BlockTurnIntoSubmenuUI,
    DocumentUploadDropzoneUI,
    ImageUploadDropzoneUI,
    MentionListUI,
    NavigatorMenuUI,
    NavigatorTriggerUI,
    SlashMenuUI,
    TableCellOptionsSubmenuUI,
    TableCellOptionsUI,
    TableColumnOptionsSubmenuUI,
    TableColumnOptionsUI,
    TableRowOptionsSubmenuUI,
    TableRowOptionsUI,
    UploadProgressUI
} from './menus-ui';
import {
    ToolbarBackgroundColorUI,
    ToolbarClearFormatUI,
    ToolbarBlockquoteUI,
    ToolbarBoldUI,
    ToolbarBulletListUI,
    ToolbarCheckListUI,
    ToolbarCodeBlockUI,
    ToolbarCodeUI,
    ToolbarDocumentUploadUI,
    ToolbarFontFamilyUI,
    ToolbarFontSizeUI,
    ToolbarForegroundColorUI,
    ToolbarHeadingUI,
    ToolbarHighlightUI,
    ToolbarHorizontalRuleUI,
    ToolbarImageInsertUI,
    ToolbarImageUploadUI,
    ToolbarItalicUI,
    ToolbarLinkUI,
    ToolbarOrderedListUI,
    ToolbarPrintUI,
    ToolbarRedoUI,
    ToolbarStrikethroughUI,
    ToolbarSubscriptUI,
    ToolbarSuperscriptUI,
    ToolbarTableInsertUI,
    ToolbarTextAlignUI,
    ToolbarUnderlineUI,
    ToolbarUndoUI
} from './toolbar-buttons';
import { ContextToolbarMoreUI, ContextToolbarUI, ToolbarUI } from './toolbar-ui';

const widgets = [
    ToolbarUI,
    ContextToolbarUI,
    ContextToolbarMoreUI,
    ToolbarBoldUI,
    ToolbarItalicUI,
    ToolbarUnderlineUI,
    ToolbarStrikethroughUI,
    ToolbarCodeUI,
    ToolbarCodeBlockUI,
    ToolbarSubscriptUI,
    ToolbarSuperscriptUI,
    ToolbarHeadingUI,
    ToolbarTextAlignUI,
    ToolbarForegroundColorUI,
    ToolbarBackgroundColorUI,
    ToolbarFontFamilyUI,
    ToolbarFontSizeUI,
    ToolbarBulletListUI,
    ToolbarOrderedListUI,
    ToolbarCheckListUI,
    ToolbarBlockquoteUI,
    ToolbarHighlightUI,
    ToolbarClearFormatUI,
    ToolbarLinkUI,
    ToolbarImageInsertUI,
    ToolbarImageUploadUI,
    ToolbarDocumentUploadUI,
    ToolbarTableInsertUI,
    ToolbarHorizontalRuleUI,
    ToolbarPrintUI,
    ToolbarUndoUI,
    ToolbarRedoUI,
    BlockControlsUI,
    BlockMenuUI,
    BlockTurnIntoSubmenuUI,
    BlockColorSubmenuUI,
    SlashMenuUI,
    MentionListUI,
    ImageUploadDropzoneUI,
    DocumentUploadDropzoneUI,
    UploadProgressUI,
    TableColumnOptionsUI,
    TableColumnOptionsSubmenuUI,
    TableRowOptionsUI,
    TableRowOptionsSubmenuUI,
    TableCellOptionsUI,
    TableCellOptionsSubmenuUI,
    NavigatorTriggerUI,
    NavigatorMenuUI
];

/** Every UI part in one import, the way the demos consume them. */
@NgModule({
    imports: widgets,
    exports: widgets
})
export class TextEditorUIModule {}
